### PR TITLE
Minor fixes and changes

### PR DESCRIPTION
**Pull request by cp-ishita-g**
- [x] fix removing preference of current space id while delete account
- [x] fix delete account
- [x] reactor code
- [x] fix intro page console error
- [x] fix cloud permission denied error while sign out
- [x] fix showing proper selected space name in home screen
- [x] fix empty path error after login to visit settings screen

### CODE REVIEW

**Comment by kaushiksaliya** [comment]
when user select any space then close space selection view.

**Comment by kaushiksaliya** [comment]
space list close and open animation is not look like android fix it.

**Comment by kaushiksaliya** [comment]
when i sign out then showing permission-denied error in run.

**Comment by cp-ishita-g** [comment]
> when i sign out then showing permission-denied error in run.

it is fixed delete app and than try again, because i am not getting that error now

**Comment by kaushiksaliya** [comment]
still getting when intro screen showing.

Screenshot from 2024-07-15 17-03-58

**Comment by kaushiksaliya** [comment]
show dialog when sign out user.

**Comment by kaushiksaliya** [comment]
this first char profile it is not looking good.

Screenshot from 2024-07-15 17-59-24

**Review by kaushiksaliya — APPROVED** [review]

**Pull request merged**
